/** Card definition types (v5 · Three Energy). The data files in src/core/cards/*.ts import only
 * this module and rules.ts; cards.ts merges them into CARDS, where every definition has its `+`
 * version built from the upgrade. Behaviour lives in src/core/effects/*.ts, keyed by base id. */
import type {
  Archetype, ArchitectCardId, BaseCardId, CardId, ColorlessCardId, CurseCardId, GhostCardId, Role, WardenCardId,
} from "./types.ts";

export type { ArchitectCardId, BaseCardId, CardId, ColorlessCardId, CurseCardId, GhostCardId, WardenCardId };

export type CardRarity = "basic" | "common" | "uncommon" | "rare" | "legendary" | "special";
/** ground places hardware · link connects two devices · node upgrades a device · instant resolves at
 * once · zone chooses a band · protocol arms · daemon starts a process for the rest of the encounter
 * (v5) · junk is clutter (a Worm is deleted by paying for it). */
export type CardTarget = "ground" | "link" | "node" | "instant" | "zone" | "protocol" | "daemon" | "junk";
/** What makes an armed protocol fire during an enemy action. */
export type ProtocolTrigger = "sever" | "jam" | "strike" | "breach" | "field" | "ultimate";

/** Numeric card parameters. Effects read these, so an upgrade only changes data and tuning a
 * number changes the face text too (faces are generated by `text`). */
export interface CardValues {
  // ---- generic: the engine applies these after the card's own effect (effects may claim a key
  // as `manual` to apply it themselves, e.g. a conditional draw)
  block?: number;
  burst?: number;
  draw?: number;
  energy?: number;
  nextEnergy?: number;
  heal?: number;
  buffer?: number;
  // ---- read by specific effects
  drawOffline?: number;
  shield?: number;
  reduce?: number;
  damage?: number;
  links?: number;
  recover?: number;
  perChannel?: number;
  perFirewall?: number;
  minimum?: number;
  /** Broadcast Storm, Packet Storm: added to every living port's packet this turn. */
  everyPort?: number;
  /** Flood Fill: added to every living port's packet per live channel this turn. */
  perChannelEveryPort?: number;
  /** Traffic Shaping, Demolition Charge: added to the target's packet this turn. */
  focusBonus?: number;
  /** Quorum: extra block for every other living hostile on the field. */
  perHostile?: number;
  /** Bulkhead: every online firewall blocks this much more against each attack this enemy phase. */
  firewallBonus?: number;
  /** Phantom Node: disruptions or installations it absorbs before it fades. */
  absorbs?: number;
  /** Rapid Redeploy: cost reduction this turn for the recovered hardware card. */
  discount?: number;
  // ---- v5: free for the keeper and colorless cards (phase C adds keys here as needed; every
  // number an effect reads lives in `values`, never inline)
  /** Next-turn gains (Brace). */
  nextBlock?: number;
  nextDraw?: number;
  /** Tokens a card creates (Fork Bomb, Shell Access). */
  tokens?: number;
  /** Backpressure added (Pushback). */
  backpressure?: number;
  /** Misses and dodges granted this turn (Spoof, Ghost Protocol). */
  misses?: number;
  dodges?: number;
  /** Man-in-the-Middle: buffer per card played this turn. */
  mitm?: number;
  /** Per-thing multipliers a face prints ("+1 damage per device"). */
  perDevice?: number;
  perSwitch?: number;
  perCluster?: number;
  perCard?: number;
  /** Protocol slots a daemon adds (Policy Engine). */
  slots?: number;
  /** Repairs (Hotfix). */
  repair?: number;
  /** Cost reduction for the next link / hardware card (Patch Panel, Rack and Stack). */
  freeLinks?: number;
  hardwareDiscount?: number;
  /** Daemon-specific amount (the hook reads it per copy). */
  amount?: number;
}

/** A card as the game uses it (CARDS[id], upgraded ids included). */
export interface CardDefinition {
  id: CardId;
  base: BaseCardId;
  upgraded: boolean;
  name: string;
  subtitle: string;
  /** The face text (generated from `values` when the definition has `text`). */
  rules: string;
  /** Long exceptions and edge cases, shown when the card is inspected and in the Handbook. */
  detail?: string;
  cost: number;
  rarity: CardRarity;
  exhaust?: boolean;
  /** v5 keywords: Retain stays in hand at the end of your turn; Innate starts in your opening
   * hand; Volatile exhausts if it is still in your hand at the end of your turn. */
  retain?: boolean;
  innate?: boolean;
  volatile?: boolean;
  keyword?: string;
  target: CardTarget;
  role?: Role;
  art: "hardware" | "cable" | "defense" | "program";
  color: string;
  /** Keeper cards: only offered to this keeper. Colorless cards leave it unset. */
  archetype?: Archetype;
  /** Encounter-only clutter injected by hostiles. Never enters the deck. */
  junk?: boolean;
  /** Permanent deck clutter. Removable at a Sanctuary or Market (even at the deck floor). */
  curse?: boolean;
  unplayable?: boolean;
  /** Token (Payload): created in hand for the encounter only, never offered. */
  token?: boolean;
  /** Protocols: the hostile action that fires it. The effect is data: `cancels` cancels the matched
   * action (its cuts, its jams, its field, or the strike/breach's damage — riders still resolve),
   * `values.shield` / `values.reduce` shield that action, `values.damage` hits the hostile that set
   * it off (trap step). Tripwire is { protocol: "strike", values: { damage } }; Null Route is
   * { protocol: "breach", cancels: true }. */
  protocol?: ProtocolTrigger;
  cancels?: boolean;
  /** Ground cards: the deployed device is jam-proof (Hardened Router, Signal Relay, Bastion). */
  jamProof?: boolean;
  /** Link cards: the cable is cut-proof and never frays (Armored Fiber, VXLAN, Dark Fiber) and/or
   * amplified (+1 on the primary route: Amplified Fiber, VXLAN). */
  cutProof?: boolean;
  amplified?: boolean;
  values: CardValues;
}

/** The upgrade: anything it leaves out is kept from the base definition. Without `rules` or `text`
 * the base `text` is re-run with the upgraded values (the usual case: only numbers change). */
export interface Upgrade {
  cost?: number;
  rules?: string;
  text?: (values: CardValues) => string;
  detail?: string;
  values?: CardValues;
  exhaust?: boolean;
  retain?: boolean;
  innate?: boolean;
  volatile?: boolean;
  jamProof?: boolean;
  cutProof?: boolean;
  amplified?: boolean;
}

/** One entry of a data file. Give `text` (a face generated from the values, preferred) or a
 * literal `rules`. */
export type BaseDefinition = Omit<CardDefinition, "id" | "base" | "upgraded" | "values" | "rules"> & {
  rules?: string;
  text?: (values: CardValues) => string;
  values?: CardValues;
  upgrade?: Upgrade;
};

/** A data file's table: every id of its owner may appear; phase C fills the missing ones
 * (`missingCards(owner)` in cards.ts lists them). */
export type CardTable<Id extends BaseCardId> = Partial<Record<Id, BaseDefinition>>;
