import type { CardId, RelicId, Role } from "./types.ts";

export interface CardDefinition {
  id: CardId;
  name: string;
  subtitle: string;
  rules: string;
  cost: number;
  rarity: "basic" | "common" | "uncommon" | "rare" | "legendary";
  exhaust?: boolean;
  keyword?: string;
  target: "ground" | "link" | "node" | "instant" | "zone";
  role?: Role;
  art: "hardware" | "cable" | "defense" | "program";
  color: string;
}

export const CARDS: Record<CardId, CardDefinition> = {
  "resonance-field": {
    id: "resonance-field", name: "Resonance Field", subtitle: "FIELD / AMPLIFY",
    rules: "Choose a zone. Routes through its hardware deal +3 damage for 3 turns.",
    cost: 1, rarity: "common", target: "zone", art: "program", color: "#e9c47c",
  },
  "aegis-field": {
    id: "aegis-field", name: "Aegis Field", subtitle: "FIELD / FORTIFY",
    rules: "Choose a zone. A live route through its hardware grants 3 shield for 3 turns.",
    cost: 1, rarity: "uncommon", target: "zone", art: "defense", color: "#91d5c4",
  },
  "purge-field": {
    id: "purge-field", name: "Purge Field", subtitle: "FIELD / CLEANSE",
    rules: "Cleanse a zone of hostile fields and device jams. Draw 1 card. Exhaust.",
    cost: 0, rarity: "common", exhaust: true, target: "zone", art: "program", color: "#d1eee2",
  },
  "null-field": {
    id: "null-field", name: "Null Field", subtitle: "FIELD / DAMPEN",
    rules: "Choose a zone. While your hardware occupies it, gain 2 shield for 3 turns.",
    cost: 1, rarity: "uncommon", target: "zone", art: "defense", color: "#b5a6e1",
  },
  router: {
    id: "router",
    name: "Core Router",
    subtitle: "HARDWARE / ROUTING",
    rules: "Place a router. A valid signal path needs at least one.",
    cost: 2,
    rarity: "basic",
    target: "ground",
    role: "router",
    art: "hardware",
    color: "#58f0d5",
  },
  switch: {
    id: "switch",
    name: "Edge Switch",
    subtitle: "HARDWARE / FABRIC",
    rules: "Place a switch. A routed switch adds +1 damage (maximum +2).",
    cost: 1,
    rarity: "basic",
    target: "ground",
    role: "switch",
    art: "hardware",
    color: "#9facff",
  },
  firewall: {
    id: "firewall",
    name: "Trust Gate",
    subtitle: "HARDWARE / SECURITY",
    rules:
      "Place a firewall. On the signal route: +1 damage; block 3 breach or 1 strike.",
    cost: 2,
    rarity: "uncommon",
    target: "ground",
    role: "firewall",
    art: "defense",
    color: "#ffba7b",
  },
  fiber: {
    id: "fiber",
    name: "Optic Fiber",
    subtitle: "INFRASTRUCTURE / LINK",
    rules: "Connect two devices with a live cable.",
    cost: 1,
    rarity: "basic",
    target: "link",
    art: "cable",
    color: "#59cfff",
  },
  crosslink: {
    id: "crosslink",
    exhaust: true,
    name: "Crosslink",
    subtitle: "INFRASTRUCTURE / LINK",
    rules: "Connect two devices for free. Draw 1. Exhaust.",
    cost: 0,
    rarity: "uncommon",
    target: "link",
    art: "cable",
    color: "#e5a1ff",
  },
  shield: {
    id: "shield",
    exhaust: true,
    name: "Faraday Shell",
    subtitle: "SYSTEM / DEFENSE",
    rules: "Protect a device from jams this battle. Clear its jam. Exhaust.",
    cost: 1,
    rarity: "uncommon",
    target: "node",
    art: "defense",
    color: "#f4ce82",
  },
  patch: {
    id: "patch",
    name: "Hot Patch",
    subtitle: "SYSTEM / REPAIR",
    rules: "Clear the active jam or severed link. Draw one card.",
    cost: 1,
    rarity: "basic",
    target: "instant",
    art: "program",
    color: "#7ceebc",
  },
  surge: {
    id: "surge",
    exhaust: true,
    name: "Power Surge",
    subtitle: "SYSTEM / ENERGY",
    rules: "Gain 2 energy. Draw 2. Exhaust.",
    cost: 0,
    rarity: "uncommon",
    target: "instant",
    art: "program",
    color: "#ffd278",
  },
  firmware: {
    id: "firmware",
    exhaust: true,
    name: "Overclock",
    subtitle: "SYSTEM / UPGRADE",
    rules: "Overclock a router: +2 route damage this battle. Exhaust.",
    cost: 1,
    rarity: "rare",
    target: "node",
    art: "program",
    color: "#ff8ca8",
  },
  containerlab: {
    id: "containerlab",
    exhaust: true,
    name: "Containerlab",
    subtitle: "SYSTEM / ORCHESTRATION",
    rules:
      "Deploy an overclocked router linked to both terminals: 7 damage. Exhaust.",
    cost: 3,
    rarity: "rare",
    target: "instant",
    art: "hardware",
    color: "#e7c37d",
  },
  clabernetes: {
    id: "clabernetes",
    exhaust: true,
    name: "Clabernetes",
    subtitle: "SYSTEM / REPLICATION",
    rules:
      "Clone a router and its links. Protect both from jams. Independent routes: +2 damage. Exhaust.",
    cost: 2,
    rarity: "legendary",
    target: "node",
    art: "hardware",
    color: "#9ccbd2",
  },
  guard: {
    id: "guard",
    name: "Packet Guard",
    subtitle: "COMMON / DEFENSE",
    rules: "Gain 4 block this turn.",
    cost: 1,
    rarity: "common",
    target: "instant",
    art: "defense",
    color: "#82d8ed",
  },
  pulse: {
    id: "pulse",
    name: "Packet Burst",
    subtitle: "COMMON / OFFENSE",
    rules: "A live route deals +3 damage this turn.",
    cost: 1,
    rarity: "common",
    target: "instant",
    art: "program",
    color: "#ff9a82",
  },
  diagnostic: {
    id: "diagnostic",
    name: "Deep Scan",
    subtitle: "COMMON / DRAW",
    rules: "Draw 3 cards. Hand limit: 10.",
    cost: 1,
    rarity: "common",
    target: "instant",
    art: "program",
    color: "#9ec0ff",
  },
  reroute: {
    id: "reroute",
    name: "Fast Reroute",
    subtitle: "UNCOMMON / REPAIR",
    rules: "Clear both faults. Gain 2 block. Draw 1. Exhaust.",
    cost: 0,
    rarity: "uncommon",
    target: "instant",
    art: "program",
    color: "#79e7c3",
    exhaust: true,
  },
  barrier: {
    id: "barrier",
    name: "Aegis Protocol",
    subtitle: "UNCOMMON / DEFENSE",
    rules: "Gain 8 block this turn.",
    cost: 2,
    rarity: "uncommon",
    target: "instant",
    art: "defense",
    color: "#c3beff",
  },
  capacitor: {
    id: "capacitor",
    name: "Power Capacitor",
    subtitle: "COMMON / RESERVE",
    rules: "Gain 3 block now and +2 energy next turn. Exhaust.",
    cost: 0,
    rarity: "common",
    target: "instant",
    art: "program",
    color: "#ffcf79",
    exhaust: true,
  },
  relay: {
    id: "relay",
    name: "Signal Relay",
    subtitle: "COMMON / HARDWARE",
    rules:
      "Place a jam-protected switch. Routed switches add +1 damage each (maximum +2). Draw 1.",
    cost: 2,
    rarity: "common",
    target: "ground",
    art: "hardware",
    color: "#a5b4ff",
    role: "switch",
  },
  "hardened-router": {
    id: "hardened-router",
    name: "Hardened Router",
    subtitle: "UNCOMMON / HARDWARE",
    rules: "Place a router protected from jams. Gain 2 block.",
    cost: 2,
    rarity: "uncommon",
    target: "ground",
    art: "hardware",
    color: "#b1d8dc",
    role: "router",
  },
  bastion: {
    id: "bastion",
    name: "Bastion Firewall",
    subtitle: "RARE / HARDWARE",
    rules:
      "Place a jam-protected firewall. Gain 5 block. On route: +1 damage; block 3 breach or 1 strike.",
    cost: 3,
    rarity: "rare",
    target: "ground",
    art: "defense",
    color: "#e5bf82",
    role: "firewall",
  },
  duplex: {
    id: "duplex",
    name: "Duplex Link",
    subtitle: "COMMON / LINK",
    rules: "Connect two devices. Gain 3 block this turn.",
    cost: 1,
    rarity: "common",
    target: "link",
    art: "cable",
    color: "#8bc9d6",
  },
  "armored-fiber": {
    id: "armored-fiber",
    name: "Armored Fiber",
    subtitle: "UNCOMMON / LINK",
    rules: "Connect two devices with a cable immune to sever attacks.",
    cost: 1,
    rarity: "uncommon",
    target: "link",
    art: "cable",
    color: "#b7c4ca",
  },
  conduit: {
    id: "conduit",
    name: "Amplified Fiber",
    subtitle: "UNCOMMON / LINK",
    rules: "Connect two devices. This cable adds +1 route damage (maximum +2).",
    cost: 1,
    rarity: "uncommon",
    target: "link",
    art: "cable",
    color: "#f0b086",
  },
  salvage: {
    id: "salvage",
    name: "Salvage Cycle",
    subtitle: "COMMON / RECOVERY",
    rules:
      "Return up to 2 most recently discarded link cards to your hand. Exhaust.",
    cost: 0,
    rarity: "common",
    target: "instant",
    art: "program",
    color: "#98ceb0",
    exhaust: true,
  },
  rebuild: {
    id: "rebuild",
    name: "Emergency Rebuild",
    subtitle: "UNCOMMON / DEPLOY",
    rules: "Deploy a basic router linked to both terminals: 5 damage. Exhaust.",
    cost: 2,
    rarity: "uncommon",
    target: "instant",
    art: "hardware",
    color: "#a9cbc2",
    exhaust: true,
  },
  mirror: {
    id: "mirror",
    name: "Mirror Protocol",
    subtitle: "UNCOMMON / REDUNDANCY",
    rules:
      "Requires two independent live routes. Gain 4 block and +3 damage this turn.",
    cost: 1,
    rarity: "uncommon",
    target: "instant",
    art: "program",
    color: "#bc9fde",
  },
  "zero-day": {
    id: "zero-day",
    name: "Zero Day",
    subtitle: "RARE / OFFENSE",
    rules: "A live route deals +8 damage this turn. Exhaust.",
    cost: 2,
    rarity: "rare",
    target: "instant",
    art: "program",
    color: "#ed8e9f",
    exhaust: true,
  },
  compression: {
    id: "compression",
    name: "Packet Compression",
    subtitle: "UNCOMMON / UPGRADE",
    rules:
      "Amplify a switch: +2 route damage this battle (once per route). Exhaust.",
    cost: 1,
    rarity: "uncommon",
    target: "node",
    art: "program",
    color: "#b0a5e6",
    exhaust: true,
  },
  emergency: {
    id: "emergency",
    name: "Emergency Repair",
    subtitle: "RARE / RECOVERY",
    rules: "Restore 3 integrity. Gain 3 block. Exhaust.",
    cost: 2,
    rarity: "rare",
    target: "instant",
    art: "defense",
    color: "#8fd3af",
    exhaust: true,
  },
  protocol: {
    id: "protocol",
    name: "Failover Protocol",
    subtitle: "COMMON / DEFENSE",
    rules: "Clear both faults. Gain 3 block this turn.",
    cost: 1,
    rarity: "common",
    target: "instant",
    art: "defense",
    color: "#91bacf",
  },

  "startup-config": {
    id: "startup-config",
    name: "Startup Config",
    subtitle: "CONTAINERLAB / CONFIGURATION",
    rules:
      "Configure a router: +1 route damage this battle (once per route). Gain 1 block. Exhaust.",
    cost: 1,
    rarity: "common",
    target: "node",
    art: "program",
    color: "#88cfb5",
    exhaust: true,
  },
  "linux-bridge": {
    id: "linux-bridge",
    name: "Linux Bridge",
    subtitle: "CONTAINERLAB / HOST BRIDGE",
    rules:
      "Place a switch, automatically linked to its nearest device. Routed switches add +1 damage (maximum +2).",
    cost: 1,
    rarity: "common",
    target: "ground",
    role: "switch",
    art: "hardware",
    color: "#a2bdce",
  },
  vxlan: {
    id: "vxlan",
    name: "VXLAN Tunnel",
    subtitle: "CONTAINERLAB / OVERLAY",
    rules:
      "Connect two devices with a sever-immune cable that adds +1 route damage (maximum +2 amplified cables).",
    cost: 2,
    rarity: "uncommon",
    target: "link",
    art: "cable",
    color: "#bba3e3",
  },
  inspect: {
    id: "inspect",
    name: "Clab Inspect",
    subtitle: "CONTAINERLAB / OBSERVABILITY",
    rules: "Draw 2 if a router route is live; otherwise draw 1. Exhaust.",
    cost: 0,
    rarity: "common",
    target: "instant",
    art: "program",
    color: "#93d1d6",
    exhaust: true,
  },
  wireshark: {
    id: "wireshark",
    name: "Wireshark",
    subtitle: "OBSERVABILITY / PACKET CAPTURE",
    rules:
      "Capture a live route. Draw 2. Gain +1 damage this turn per hardware type on that route (max 3). Exhaust.",
    cost: 1,
    rarity: "uncommon",
    target: "instant",
    art: "program",
    color: "#86c9e9",
    exhaust: true,
  },
};

export const STARTER_DECK: CardId[] = [
  "router",
  "router",
  "router",
  "switch",
  "firewall",
  "fiber",
  "fiber",
  "fiber",
  "fiber",
  "fiber",
  "fiber",
  "patch",
  "purge-field",
  "shield",
  "surge",
  "guard",
  "resonance-field",
  "startup-config",
  "inspect",
];
export const REWARD_POOL: CardId[] = Object.keys(CARDS) as CardId[];

export const RELICS: Record<
  RelicId,
  { name: string; subtitle: string; rules: string; color: string }
> = {
  "cold-start": {
    name: "Cold Start",
    subtitle: "POWER UNIT",
    rules: "+1 energy at the start of each battle.",
    color: "#6fe8fb",
  },
  "hot-swap": {
    name: "Hot Swap",
    subtitle: "LINK MODULE",
    rules: "The first Optic Fiber each turn costs zero energy.",
    color: "#c59bff",
  },
  "parallel-core": {
    name: "Parallel Core",
    subtitle: "PACKET ENGINE",
    rules: "+2 packet damage when two independent routes are live.",
    color: "#80f8d6",
  },
  "shield-array": {
    name: "Shield Array",
    subtitle: "DEFENSE MODULE",
    rules: "Prevent up to 2 damage from the first unblocked hit each battle.",
    color: "#ffc186",
  },
  "deep-cache": {
    name: "Deep Cache",
    subtitle: "MEMORY MODULE",
    rules: "Draw one extra card every turn.",
    color: "#ff9ab6",
  },
  "grounded-core": {
    name: "Grounded Core",
    subtitle: "DEFENSE MODULE",
    rules: "Start every turn with 1 block.",
    color: "#93d2d0",
  },
  "packet-lens": {
    name: "Packet Lens",
    subtitle: "SIGNAL MODULE",
    rules: "+1 damage when your signal route includes a switch.",
    color: "#bbacf0",
  },
  "repair-drone": {
    name: "Repair Drone",
    subtitle: "RECOVERY MODULE",
    rules: "Restore 1 integrity after winning an encounter.",
    color: "#b4d58b",
  },
  "reserve-cell": {
    name: "Reserve Cell",
    subtitle: "ENERGY MODULE",
    rules: "Carry up to 2 unspent energy into the next turn.",
    color: "#eed290",
  },
};
