/* FAULTLINE: GPL-3.0-only with section 7(b) attribution terms; see LICENSE and ATTRIBUTION.md. */
/** The single-hostile invariant (design section 4, "a single hostile sees exactly today's
 * transmission"; section 15.4): on the 160 randomized boards of combat.test.ts, a one-hostile
 * encounter's forecast (packet, shield, targets, next turn) and its resolution equal a snapshot
 * taken with the pristine v3 engine before the refactor (fixtures/v3-boards.json, generated by
 * the lead's scratchpad script gen-fixture.ts against the v3 copy of src/).
 *
 * The rules of v4 deliberately change two v3 behaviours, and only those boards differ:
 *  · the Wire Weaver's BIND HARDWARE jam became OVERTENSION, an overload (section 9.3);
 *  · a Siphon Tap planted within reach of a cabled honeypot arrives destroyed (rule 37),
 *    which grants Reclaim shield (rule 39).
 * Those boards are checked against the v4 rule instead. */
import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { RULES } from "./cards.ts";
import { newExpedition } from "./expedition.ts";
import { chooseRoom, combatPreview, endTurn } from "./run.ts";
import type { Archetype, CardId, NetworkNode, RelicId, RunState } from "./types.ts";

interface Board {
  input: { trial: number; enemy: string; turn: number; hp: number; archetype: Archetype };
  preview: Record<string, unknown> & { intent: { kind: string; amount: number; target: string | null } | null };
  after: Record<string, unknown>;
}
const fixture = JSON.parse(readFileSync(new URL("./fixtures/v3-boards.json", import.meta.url), "utf8")) as { boards: Board[] };

function table(enemy: string, turn: number, archetype: Archetype): RunState {
  const run = newExpedition(archetype, 0x5eed1234).run;
  chooseRoom(run, "0-1");
  const foe = run.enemies[0];
  foe.id = enemy;
  foe.hp = foe.maxHp = 200;
  foe.turn = turn;
  run.integrity = run.maxIntegrity = 100;
  run.energy = 20;
  run.relics = [];
  run.topology.nodes = run.topology.nodes.filter(node => node.fixed);
  run.topology.links = [];
  run.zoneEffects = [];
  run.hand = [];
  run.drawPile = Array(30).fill("guard");
  run.discardPile = [];
  run.nextNodeId = 1;
  return run;
}

/** The exact board generator of combat.test.ts (same LCG, same order of draws). */
function* boards(): Generator<{ run: RunState; trial: number }> {
  const enemies = ["leech", "wraith", "storm", "sentinel", "prophet", "widow", "colossus", "serpent", "moth", "marshal", "choir", "weaver", "reaver", "regent", "cantor", "core"];
  const roles: NetworkNode["role"][] = ["router", "switch", "firewall", "honeypot", "cache", "power", "balancer"];
  let state = 7;
  const rand = () => ((state = (state * 1103515245 + 12345) >>> 0) / 0x100000000);
  for (let trial = 0; trial < 160; trial++) {
    const r = table(enemies[trial % enemies.length], Math.floor(rand() * 6), (["architect", "warden", "ghost"] as const)[trial % 3]);
    r.enemies[0].hp = 5 + Math.floor(rand() * 40);
    r.relics = (["backpressure", "honeynet", "zero-trust", "parallel-core", "packet-lens", "shield-array"] as RelicId[]).filter(() => rand() < 0.3);
    const count = 2 + Math.floor(rand() * 8);
    for (let i = 0; i < count; i++) {
      const x = -4 + (i % 4) * 2.6, z = -3 + Math.floor(i / 4) * 2.6;
      r.topology.nodes.push({ id: `d${i}`, role: roles[Math.floor(rand() * roles.length)], x, z, configured: rand() < 0.2, upgraded: rand() < 0.2 });
    }
    const ids = r.topology.nodes.map(node => node.id);
    for (let i = 0; i < count * 2; i++) {
      const a = ids[Math.floor(rand() * ids.length)], b = ids[Math.floor(rand() * ids.length)];
      if (a !== b && !r.topology.links.some(link => (link.a === a && link.b === b) || (link.a === b && link.b === a)))
        r.topology.links.push({ a, b, boosted: rand() < 0.2, armored: rand() < 0.2 });
    }
    // v3 malware at (6, 4) is today's Siphon Tap.
    if (rand() < 0.3) r.installations = [{ id: "tap1", kind: "tap", x: 6, z: 4, integrity: 1, activeFrom: 0, owner: "h1" }];
    if (rand() < 0.4) r.protocols = [(["failover-policy", "port-security", "rate-limiter", "ips-signature", "quarantine-rule", "tarpit"] as CardId[])[Math.floor(rand() * 6)]];
    r.block = Math.floor(rand() * 6);
    r.buffer = rand() < 0.3 ? 6 : 0;
    r.backpressure = rand() < 0.2 ? 3 : 0;
    if (r.archetype === "ghost" && rand() < 0.5) r.buffering = true;
    r.hand = rand() < 0.2 ? ["worm"] : [];
    yield { run: r, trial };
  }
}

test("the v3 fixture covers the 160 boards and every enemy of the v3 roster", () => {
  assert.equal(fixture.boards.length, 160);
  assert.equal(new Set(fixture.boards.map(board => board.input.enemy)).size, 16);
});

test("single-hostile invariant: v4 reproduces the v3 forecast and resolution on every board without an install or overload", () => {
  // Layers that deliberately change a single hostile's numbers are switched off by their RULES
  // flags: escalation (levels and the guardians' charge at half health) and guardian adds.
  const rules = RULES as unknown as Record<string, number>;
  // v5 tuning moved the v3 engine numbers the fixture was recorded with: pin them back for the comparison.
  const saved = {
    escalationStart: rules.escalationStart, addBreakBonus: rules.addBreakBonus, backpressureRatio: rules.backpressureRatio,
    bufferMultiplier: rules.bufferMultiplier, hardenShield: rules.hardenShield,
  };
  rules.escalationStart = 99;
  rules.addBreakBonus = 0;
  rules.backpressureRatio = 0.5;
  rules.bufferMultiplier = 2;
  rules.hardenShield = 2;
  try {
  let compared = 0, changedByDesign = 0;
  for (const { run: r, trial } of boards()) {
    const v3 = fixture.boards[trial];
    assert.equal(r.enemies[0].id, v3.input.enemy, `trial ${trial} board`);
    assert.equal(r.enemies[0].hp, v3.input.hp, `trial ${trial} board`);
    const p = combatPreview(r);
    const hpBefore = r.enemies[0].hp;
    const result = endTurn(r);
    const v3Kind = v3.preview.intent?.kind === "infect" ? "install" : v3.preview.intent?.kind;
    const overload = p.intent?.kind === "overload";
    const bittenTap = p.installTargets.some(item => item.bitten);
    if (overload || bittenTap) {
      changedByDesign++;
      if (overload) {
        // OVERTENSION: v3 jammed the target; v4 wears it by 1 instead.
        assert.equal(v3Kind, "jam", `trial ${trial}`);
        assert.equal(p.faultTarget, null, `trial ${trial}`);
        assert.equal(p.wear.length, 1, `trial ${trial}`);
        assert.equal(p.wear[0].nodeId, v3.preview.faultTarget, `trial ${trial}: overload targets follow the jam rule`);
      } else {
        // The bitten Tap arrives destroyed: Reclaim shield joins the pool; no Tap to heal from.
        assert.ok(p.installTargets[0].destroyed, `trial ${trial}`);
        assert.equal(p.shield, (v3.preview.shield as number) + RULES.reclaimShield, `trial ${trial}`);
        assert.equal(p.enemyHealing, (v3.preview.enemyHealing as number) - RULES.leechTapHeal, `trial ${trial}`);
      }
      continue;
    }
    compared++;
    const at = `trial ${trial} (${v3.input.enemy}, turn ${v3.input.turn}, ${v3.input.archetype})`;
    const want = v3.preview;
    assert.equal(p.packetDamage, want.packetDamage, `${at}: packet`);
    assert.equal(p.damageTerms.reduce((sum, term) => sum + term.amount, 0), want.damageSum, `${at}: damage terms`);
    assert.equal(p.rawPacketDamage, want.rawPacketDamage, `${at}: raw packet`);
    assert.equal(p.lethal, want.lethal, `${at}: lethal`);
    assert.equal(p.channels, want.channels, `${at}: channels`);
    assert.deepEqual(p.signalPath, want.signalPath, `${at}: primary route`);
    assert.deepEqual(p.clusters, want.clusters, `${at}: clusters`);
    // v5 economy: the v3 fixture's turn was 5 energy and 6 cards; online devices add the same.
    const v3Next = want.nextTurn as { energy: number; draw: number };
    assert.deepEqual(p.nextTurn, { energy: v3Next.energy - 5 + RULES.baseEnergy, draw: v3Next.draw - 6 + RULES.handDraw, block: 0 }, `${at}: next turn`);
    assert.equal(p.intent?.kind, v3Kind, `${at}: intent`);
    assert.equal(p.intent?.amount, want.intent?.amount, `${at}: intent amount`);
    assert.equal(p.intent?.target ?? null, want.intent?.target ?? null, `${at}: intent target`);
    assert.equal(p.bufferGain, want.bufferGain, `${at}: buffer`);
    assert.equal(p.bufferRelease, want.bufferRelease, `${at}: release`);
    if (!want.lethal) {
      assert.equal(p.shield, want.shield, `${at}: shield`);
      assert.equal(p.incoming, want.incoming, `${at}: incoming`);
      assert.equal(p.incomingRaw, want.incomingRaw, `${at}: raw incoming`);
      assert.equal(p.faultTarget, want.faultTarget, `${at}: fault target`);
      assert.deepEqual(p.malwareTarget, want.malwareTarget, `${at}: Tap socket`);
      assert.deepEqual(p.junk, want.junk, `${at}: junk`);
      assert.deepEqual(p.zoneThreat, want.zoneThreat, `${at}: field`);
      assert.equal(p.hazardZone, want.hazardZone, `${at}: hazard band`);
      assert.equal(p.interrupted, want.interrupted, `${at}: interrupt`);
      assert.equal(p.enemyDamage, want.enemyDamage, `${at}: traps`);
      assert.equal(p.enemyDefeatedByTraps, want.enemyDefeatedByTraps, `${at}: trap kill`);
      assert.equal(p.enemyHealing, want.enemyHealing, `${at}: healing`);
      assert.deepEqual(p.protocolTriggers.map(trigger => trigger.card), want.protocolTriggers, `${at}: protocols`);
      assert.equal(p.bufferAtRisk, want.bufferAtRisk, `${at}: packet loss`);
      assert.equal(p.backpressureGain, want.backpressureGain, `${at}: backpressure`);
    }
    // Resolution.
    const after = v3.after;
    assert.equal(result.defeated, after.defeated, `${at}: defeated`);
    assert.equal(r.integrity, after.integrity, `${at}: integrity`);
    assert.equal(result.defeated ? null : r.enemies[0].hp, after.enemyHp, `${at}: hostile health (from ${hpBefore})`);
    // v5 economy (a won fight keeps its energy and hand): 2 energy and 1 card fewer than v3.
    assert.equal(r.energy, (after.energy as number) - (result.defeated ? 0 : 5 - RULES.baseEnergy), `${at}: energy`);
    assert.equal(r.hand.length, (after.handSize as number) - (result.defeated ? 0 : 6 - RULES.handDraw), `${at}: hand`);
    assert.equal(r.faultNodes[0] ?? null, after.faultNode, `${at}: jam`);
    assert.equal(r.faultLinks[0] ?? null, after.faultLink, `${at}: cut`);
    assert.deepEqual(r.installations.map(item => ({ x: item.x, z: item.z })), after.malware, `${at}: Taps`);
    assert.equal(r.backpressure, after.backpressure, `${at}: stored backpressure`);
    assert.equal(r.buffer, after.buffer, `${at}: stored buffer`);
    assert.deepEqual(r.zoneEffects, after.zoneEffects, `${at}: fields`);
    assert.deepEqual(result.junkAdded, after.junkAdded, `${at}: junk added`);
    assert.deepEqual(r.protocols, after.protocols, `${at}: armed protocols`);
  }
  assert.ok(compared >= 150, `${compared} boards compared`);
  assert.equal(changedByDesign, 160 - compared);
  } finally {
    Object.assign(rules, saved);
  }
});
