import type { CardId } from "./core/types.ts";

/** Player-facing connections between rules, without revealing a reward roll. */
export const CARD_INSIGHTS: Partial<Record<CardId, string>> = {
  "resonance-field": "A band contributes +3 once per route, even with several devices in it. Keep the route in that band for up to three transmissions. Recasting an allied field in the same band replaces it.",
  "aegis-field": "The shield renews while a live route crosses hardware in this band. A severed route loses this protection. Combine it with armored links and Faraday Shell, or use Null Field when the network is offline.",
  "purge-field": "Cleanses hostile ground without removing your own field. It also clears a jam on hardware in that band. It exhausts for the encounter. Corrosion and suppression stay on the ground when you move away; they never follow the device.",
  "null-field": "Grants shield even without a complete signal route, as long as a deployed device occupies the band. Fixed ALPHA and OMEGA terminals never count as occupied hardware.",
  router: "Build a second route with its own router to earn +2 signal. If independent routes have routers in both outer bands, they also grant 2 shield.",
  "hardened-router": "Jam protection answers the Null Storm. A separate router route keeps you transmitting when the other route loses a cable.",
  fiber: "A direct ALPHA–OMEGA cable cannot attack without a router. Hot Swap makes the first Optic Fiber each turn free.",
  firewall: "Wire the firewall into a live router route. It adds damage, blocks attacks, and bypasses the Gate Sentinel's 2-point plating.",
  bastion: "A firewall on the chosen route bypasses Sentinel plating. The 5 temporary block arrives immediately, even before you finish wiring it.",
  switch: "A switch supports the route; it still needs a router. Routed switches add up to +2 damage, with another +2 available from Packet Compression.",
  relay: "A protected switch is a safe home for Packet Compression. Packet Lens adds another point when a switch joins the chosen route.",
  "linux-bridge": "Deployment creates one free cable to the closest device. Complete a router route through the bridge, then use Packet Compression or Packet Lens to improve it.",
  containerlab: "A compact 7-damage route in one card. Add Startup Config, then replicate it with legendary Clabernetes to preserve the router's configuration and overclock.",
  clabernetes: "Copies the router's Overclock, Startup Config, armored cables and amplified cables. Shared switches or firewalls can still prevent independence. Relocate one replica to form north/south circuits.",
  "startup-config": "Stacks with Overclock for a +3 configured router. Clabernetes preserves both upgrades. Several configured routers on one route still contribute only +1 from Startup Config.",
  firmware: "Stacks with Startup Config. Overclock contributes +2 once per route; spreading upgraded routers across independent routes is more resilient than stacking them in series.",
  compression: "A routed switch adds its normal +1 plus this +2 upgrade. Several amplified switches still contribute only +2 from Compression.",
  guard: "Spend only what the incoming forecast needs. Block stops damage, including the Core's emergency-mode chip damage, but never stops a jam or sever.",
  barrier: "Best against heavy breaches and late pressure. Unused block expires after transmission, so an early defense can be wasted on a pure disruption turn.",
  shield: "Jam protection lasts for the encounter and also clears this device's current jam. It does not absorb integrity damage or protect cables from a Wraith.",
  "armored-fiber": "Keep the Wraith away from a critical cable. Pair with jam-protected hardware so neither kind of fault can silence that section of your route.",
  conduit: "Earn +1 for each amplified cable on the chosen route, up to +2. A longer chain of ordinary cables adds no damage by itself.",
  vxlan: "Combine sever protection with amplified-cable damage. Clabernetes preserves both properties when it copies a router's connections.",
  duplex: "Build while defending. Its block arrives as soon as the link is created, even when the new circuit is not complete yet.",
  crosslink: "A free link and card draw accelerate setup. It exhausts, so Salvage Cycle cannot retrieve it during this encounter.",
  patch: "Recover a broken route before spending a packet boost. Restoring a signal also denies the Packet Leech's healing.",
  reroute: "A free recovery turn can restore your signal and leave all energy available for building or burst damage. It can only be used once per encounter.",
  protocol: "Trades one block compared with Packet Guard for immediate fault recovery. Especially useful when a broken route also needs protection from an incoming attack.",
  pulse: "Needs a live router route. A lethal burst cancels the enemy's entire intent, so finishing a hostile can save more integrity than blocking it.",
  "zero-day": "Save this limited burst for a lethal turn or the Core's emergency mode. A disconnected route cannot deliver it.",
  mirror: "Rewards two independent live routes with offense and defense at once. North/south separation can add another 2 shield.",
  capacitor: "Prepare for a bigger next turn while blocking now. Its stored energy combines with the Reserve Cell relic; current-turn block still expires normally.",
  surge: "Use its energy and draw in the current turn. Powerful setup is finite: an exhausted Surge cannot return in a reshuffle.",
  diagnostic: "Find the repair, link or defense you need. At the ten-card limit, undrawn cards remain in your draw pile.",
  inspect: "Finish a live router route first to draw two instead of one. Useful for finding a burst after the network is ready.",
  wireshark: "Capture a route containing a router, switch and firewall for the full +3 burst. Only the highlighted route counts; duplicate hardware types add nothing. Play the cards you draw before transmitting.",
  salvage: "Recovers your most recently discarded links. It cannot recover exhausted Crosslinks; play it after spending ordinary, armored or amplified links.",
  rebuild: "Restore a basic independent circuit quickly. Its router can still receive Startup Config and Overclock afterward.",
  emergency: "Integrity healing persists across sectors. The accompanying block expires this turn, so use it when you can benefit from both.",
};
