import { RULES } from "./core/cards.ts";
import type { BaseCardId } from "./core/types.ts";

const R = RULES;
/** Player-facing connections between rules, without revealing a reward roll.
 * Keyed by base card: an upgraded card shares its insight. */
export const CARD_INSIGHTS: Partial<Record<BaseCardId, string>> = {
  router: `Every route needs one. A second router on its own route adds a channel: +${R.bandwidthPerChannel} bandwidth, and a cut on one route leaves the other transmitting. Routers in opposite outer bands on separate channels also grant ${R.separatedCircuitShield} shield.`,
  "hardened-router": "Jam protection answers the Null Storm and the Marshal. Build it as the heart of your primary route so a jam can't silence you.",
  switch: `+${R.switchDamage} while it sits on your primary route — with no cap, so a long primary route hits harder. Long routes are also more cables for a cut to find.`,
  relay: "A protected switch is a safe home for Packet Compression. Packet Lens doubles what every switch on the primary route adds.",
  "linux-bridge": "Deployment creates one free cable to the closest device. Place it between two routers and a single cable finishes a second channel.",
  firewall: `A firewall works from any live route: online, it blocks ${R.firewallBreachBlock} of a breach or ${R.firewallStrikeBlock} of a strike, and several firewalls stack. It also bypasses Sentinel, Marshal and Hollow Choir plating.`,
  bastion: "Jam protection plus immediate block: it defends the turn you build it, before its cables are finished.",
  "stateful-firewall": "Blocks double. Put it on a second channel so a cut on your primary route doesn't take your defense offline too.",
  honeypot: `A decoy works even offline — it only needs a cable. Jams and cuts hit it first (the Wraith is the exception) and each one costs the attacker ${R.honeypotDamage}. Protect it and you protect the rest of your network.`,
  "cache-server": "Online at the start of your turn: draw one more card. The draw is checked after the enemy acts, so keep it on a channel the forecast cut can't reach.",
  "poe-injector": "Online at the start of your turn: +1 energy. Two injectors on separate channels are a real engine; a cut or jam before your turn switches one off.",
  "load-balancer": `+${R.balancerPerChannel} damage for every live channel while it is online. It rewards width: three channels make every balancer worth +3.`,
  fiber: "A direct ALPHA–OMEGA cable carries no attack; a router must sit between. Hot Swap makes the first Optic Fiber each turn free.",
  crosslink: "A free cable and a card. It exhausts, so Salvage Cycle can't bring it back this encounter.",
  duplex: "Build while defending: the block arrives when the cable is connected, even if the circuit isn't complete.",
  "armored-fiber": "Cut-proof and fray-proof. Protect the one cable every channel shares, the long span a Wraith would choose, or a straight run across wreckage.",
  conduit: `+${R.amplifiedCableDamage} while it is on your primary route, no cap — but a cut on an amplified cable costs both the route and its bonus.`,
  vxlan: "Cut-proof, fray-proof and amplified: the backbone cable of a primary route you intend to keep.",
  "dark-fiber": "A free, cut-proof and fray-proof cable that exhausts — the Ghost's way to secure a buffer against the next cut.",
  shield: "Jam protection lasts the encounter and clears this device's current jam. It doesn't absorb damage or protect cables.",
  patch: "Recover a broken route before you spend a burst. Restoring a signal also denies Packet Leech its healing.",
  reroute: "A free recovery: clear the fault and keep all your energy for building, bursting or arming a protocol.",
  protocol: "Recovery plus block in one card — useful when a cut route also faces an attack.",
  firmware: `+${R.overclockDamage} while this router is on your primary route. Every overclocked router on that route counts.`,
  "startup-config": `+${R.configuredDamage} while this router is on your primary route; stacks with Overclock. Clabernetes copies both.`,
  compression: `+${R.compressionDamage} on top of the switch's own +${R.switchDamage} while it sits on your primary route.`,
  containerlab: `A complete ${R.baseRouteDamage + R.overclockDamage}-damage route in one card, in a free socket. A great second channel when your first route is already built.`,
  clabernetes: "Clones a router with its cables and upgrades: an instant extra channel if its cables reach the terminals. Relocate the replica to split north and south.",
  rebuild: "An emergency second channel cabled to both terminals: redundancy and bandwidth for two energy.",
  guard: "Spend only what the incoming forecast needs. Block stops damage but never stops a jam or a cut.",
  barrier: "Best against heavy breaches and ultimates. Unused block expires after the transmission.",
  capacitor: "Block now, energy next turn: ideal on a turn when you can see a big play coming.",
  emergency: "Integrity healing persists across sectors; the block expires this turn.",
  pulse: "Needs a live route. A lethal burst cancels the enemy's whole action — finishing it can save more than blocking.",
  "zero-day": "Save it for a lethal turn, an ultimate interrupt or a buffer the Ghost wants to fill.",
  mirror: `Needs two or more channels, then pays per channel: width turns this into a big burst and a big block.`,
  ecmp: "Equal-cost multipath: every live channel adds burst. Build width first, then cash it in.",
  "spine-leaf": "One switch cabled to every router: instantly online on every channel it joins. Superb once you have three or more routers.",
  "mesh-weave": "Cables the chosen device to its nearest neighbours — the fastest way to bring salvaged or offline hardware online.",
  "deep-inspection": "Scales with online firewalls. Warden decks with two or three firewalls turn this into a wall.",
  reflect: "Doubles stored backpressure: block a heavy hit, then answer with twice the force.",
  "store-forward": "Fills the buffer without transmitting — the Ghost's burst for a later turn.",
  "replay-attack": "Doubles your buffer. Pair with an ultimate turn: store, replay, then break the guardian in one release.",
  diagnostic: "Find the repair, cable or protocol you need. At the hand limit, undrawn cards stay in the draw pile.",
  inspect: "Build a live route first to draw the larger amount.",
  wireshark: "Counts every distinct device type on your primary route: router, switch, firewall, honeypot, cache, power, balancer. Diverse routes pay.",
  surge: "Use the energy and cards now: an exhausted Surge doesn't come back this encounter.",
  salvage: "Recovers your most recently discarded cables. It can't recover exhausted ones.",
  "failover-policy": "Arm it the turn before a forecast cut: the cut is cancelled and you gain shield. Armed protocols wait across turns until they fire.",
  "port-security": "Arm it before a jam: the jam fails and the attacker takes damage. Honeypots draw jams first, so the two don't stack on one attack.",
  "rate-limiter": "Arm it for the next strike. With a strike forecast, the reduction shows in the shield terms right away.",
  "ips-signature": "Arm it for the next breach — the heaviest hits and many ultimates are breaches.",
  "quarantine-rule": "Cancels the next hostile field before it lands. Excellent against Prophet, Widow, Choirs and the Core.",
  tarpit: "Fires when a guardian charges or unleashes an ultimate: damage on the one turn you most need it.",
  "resonance-field": `+${R.resonanceDamage} for each resonant band your primary route crosses. Route through that band to collect it.`,
  "aegis-field": "Shield every turn while a live route crosses hardware in that band.",
  "null-field": "Shield while any of your hardware occupies the band — no route needed.",
  "purge-field": "Cleanses hostile fields, jams and malware in a band, and draws. It never removes your own fields.",
  "packet-loss": "Junk: it can't be played and vanishes at the end of your turn. It only costs you a draw.",
  worm: `Junk: delete it for its cost, or take ${R.wormDamage} damage when you transmit with it in hand.`,
  cve: "A curse from a hard bargain. Remove it at a Sanctuary or a Market.",
};
